format = """
[î‚¶](#9A348E)\
$directory(bg:#9A348E)\
[î‚° ](fg:#9A348E)\
"""

[directory]
style = "bg:#9A348E"
format = "[ $path ]($style)"
truncation_length = 1
truncation_symbol = ""

[directory.substitutions]
"C:/" = "ğŸ¥• "
"~" = "ğŸ‹"
"ğŸ¥• Workspace/Road" = "ğŸš—"
"ğŸ¥• Workspace/Aviation" = "âœˆ "